### ISSUE TITLE
Support textures of .obj

### ISSUE THREAD

**Issue by hiroharu-kato** [hiroharu-kato/neural_renderer#1]

**Comment by ThibaultGROUEIX** [comment]
That would be great ! great work !

**Comment by ThibaultGROUEIX** [comment]
For exemple, this textured  obj appears fine in meshload but gives the error below when given as input to example1.py:

```
Traceback (most recent call last):
  File "examples/example1.py", line 66, in <module>
    run()
  File "examples/example1.py", line 31, in run
    vertices, faces , textures= neural_renderer.load_obj(args.filename_input, load_texture = True)
  File "/home/thibault/projects/neural_renderer/neural_renderer/load_obj.py", line 184, in load_obj
    textures = load_textures(filename_obj, filename_mtl, texture_size)
  File "/home/thibault/projects/neural_renderer/neural_renderer/load_obj.py", line 77, in load_textures
    color = chainer.cuda.to_gpu(color)
  File "/home/thibault/anaconda2/envs/neural_mesh/lib/python3.5/site-packages/chainer/backends/cuda.py", line 274, in to_gpu
    return _array_to_gpu(array, device_, stream)
  File "/home/thibault/anaconda2/envs/neural_mesh/lib/python3.5/site-packages/chainer/backends/cuda.py", line 319, in _array_to_gpu
    return cupy.asarray(array)
  File "/home/thibault/anaconda2/envs/neural_mesh/lib/python3.5/site-packages/cupy/creation/from_data.py", line 60, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 1997, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2028, in cupy.core.core.array
ValueError: Unsupported dtype object
```
[obj.zip](https://github.com/hiroharu-kato/neural_renderer/files/1864030/obj.zip)
