### ISSUE TITLE
2 errors detected in the compilation of "/tmp/tmpgX1d3K/kern.cu"

### ISSUE THREAD

**Issue by songweige** [hiroharu-kato/neural_renderer#12]
Hi I was trying to run "python ./examples/example1.py" but got following erUsing username "songweig".

Traceback (most recent call last):
  File "./examples/example1.py", line 66, in <module>
    run()
  File "./examples/example1.py", line 52, in run
    images = renderer.render(vertices, faces, textures)  # [batch_size, RGB, image_size, image_size]
  File "build/bdist.linux-x86_64/egg/neural_renderer/renderer.py", line 90, in render
  File "build/bdist.linux-x86_64/egg/neural_renderer/lighting.py", line 40, in lighting
  File "build/bdist.linux-x86_64/egg/neural_renderer/cross.py", line 59, in cross
  File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 235, in __call__
    ret = node.apply(inputs)
  File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
    return self._function.forward(inputs)
  File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 342, in forward
    return self.forward_gpu(inputs)
  File "build/bdist.linux-x86_64/egg/neural_renderer/cross.py", line 39, in forward_gpu
  File "cupy/core/_kernel.pyx", line 558, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/core/_kernel.pyx", line 579, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 392, in cupy.core._kernel._get_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 26, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/_kernel.pyx", line 46, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
  File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: cmr/venv_cmr/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]"
/tmp/tmpgX1d3K/kern.cu(10): here

/tmp/tmpgX1d3K/kern.cu(13): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"

/tmp/tmpgX1d3K/kern.cu(14): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"

2 errors detected in the compilation of "/tmp/tmpgX1d3K/kern.cu".

**Comment by songweige** [comment]
Here are my configurations:

numpy==1.14.0
chainer==5.1.0
cupy-cuda90==5.1.0
scikit-image==0.13.1

Could you please give me some suggestions? Thanks a lot!!

**Comment by ThibaultGROUEIX** [comment]
Hi @SongweiGe ,
 I have the same issue, did you end up solving it ?
Best regards,
Thibault

**Comment by songweige** [comment]
Hey Thibault, sorry for the very late reply. I changed to chainer==3.3.0 and cupy==2.3.0 to run the codes. Hope you've already solved the problem

**Comment by lzq2369** [comment]
pip uninstall cupy  
next 
pip install
