### ISSUE TITLE
running setup.py causes bug in Python 3

### ISSUE THREAD

**Issue by Zardinality** [hiroharu-kato/neural_renderer#6]
running `setup.py` in the root path of this repo showing:
```
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    import neural_renderer
  File "/new_disk_1/antonio/neural_renderer/neural_renderer/__init__.py", line 1, in <module>
    from cross import cross
ModuleNotFoundError: No module named 'cross'
```
I changed all absolute imports to relative ones in the regarding file and it did the work, now `./neural_renderer/__init__.py` looks like:
```python
from .cross import cross
from .get_points_from_angles import get_points_from_angles
from .lighting import lighting
from .load_obj import load_obj
from .look import look
from .look_at import look_at
from .mesh import Mesh
from .optimizers import Adam
from .perspective import perspective
from .rasterize import (
    rasterize_rgbad, rasterize, rasterize_silhouettes, rasterize_depth, use_unsafe_rasterizer, Rasterize)
from .renderer import Renderer
from .save_obj import save_obj
from .vertices_to_faces import vertices_to_faces

__version__ = '1.1.2'
```
Adding `./neural_renderer` to `$PYTHON_PATH` temporarily should do the same thing. I just feel this is worth a note in README.

**Comment by hiroharu-kato** [comment]
Thank you for the useful suggestion!
I added this problem and solution to README.

**Comment by slate0** [comment]
I am running python 2.7 and I still get this error message.
